# Generated by Django 4.2.6 on 2023-11-01 04:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("record", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="middle_name",
            field=models.CharField(max_length=70, null=True),
        ),
    ]
